#### **Chargement des données :**

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scipy import stats
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import KNNImputer

%matplotlib inline

df_h1 = pd.read_csv('liver.csv')
df_h2 = pd.read_json('liver.json')

In [8]:
df_h1.head(3)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,ALT,AST,Total_Proteins,Albumin,Albumin_and_Globulin_Ratio,Result
0,41 to 60 yo,Male,7.0,2.0,174.0,NaN,14,7800.0 mg/dL,4.2,NaN,2
1,41 to 60 yo,Male,6.0,2.0,245.0,22.0,24,7100.0 mg/dL,3.4,0.9,1
2,21 to 40 yo,Male,11.0,5.0,191.0,37.0,41,7700.0 mg/dL,4.3,NaN,2

In [9]:
df_h2.head(3)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Proteins,Albumin,Albumin_and_Globulin_Ratio,Outcome
0,61 to 80 yo,Female,0.7,0.1,187.0,NaN,18,6.8,3.3,0.90,1
1,61 to 80 yo,Male,10.9,5.5,699.0,64.0,100,7.5,NaN,0.74,1
2,61 to 80 yo,Male,7.3,4.1,490.0,NaN,68,7.0,3.3,NaN,1

#### **Analyse des jeux de données :**

In [10]:
print(df_h1.info())
df_h2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         321 non-null    object
 1   Gender                      321 non-null    object
 2   Total_Bilirubin             317 non-null    float64
 3   Direct_Bilirubin            320 non-null    float64
 4   Alkaline_Phosphotase        317 non-null    float64
 5   ALT                         254 non-null    float64
 6   AST                         321 non-null    int64
 7   Total_Proteins              321 non-null    object
 8   Albumin                     316 non-null    float64
 9   Albumin_and_Globulin_Ratio  262 non-null    float64
 10  Result                      321 non-null    int64
dtypes: float64(6), int64(2), object(3)
memory usage: 27.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         291 non-null    object
 1   Gender                      291 non-null    object
 2   Total_Bilirubin             290 non-null    float64
 3   Direct_Bilirubin            287 non-null    float64
 4   Alkaline_Phosphotase        290 non-null    float64
 5   Alamine_Aminotransferase    236 non-null    float64
 6   Aspartate_Aminotransferase  291 non-null    int64
 7   Total_Proteins              289 non-null    float64
 8   Albumin                     290 non-null    float64
 9   Albumin_and_Globulin_Ratio  227 non-null    float64
 10  Outcome                     291 non-null    int64
dtypes: float64(7), int64(2), object(2)
memory usage: 25.1+ KB

**Remarque :**

- Total_Proteins est de type objet dans le df_h1 et de type float64 dans le df_h2

- ALT, ASP et Result de df_h1 sont appelés Alamine_Aminotransferase, Aspartate_Aminotransferase et Outcome dans df_h2